[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Redirecionamentos críticos para admin - ORDEM IMPORTA!
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = true

[[redirects]]
  from = "/admin/login"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200
  force = true

# Redirecionamentos para idiomas
[[redirects]]
  from = "/pt"
  to = "/pt/"
  status = 301

[[redirects]]
  from = "/pt/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/en"
  to = "/en/"
  status = 301

[[redirects]]
  from = "/en/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/es"
  to = "/es/"
  status = 301

[[redirects]]
  from = "/es/*"
  to = "/index.html"
  status = 200
  force = true

# Redirecionamento da raiz
[[redirects]]
  from = "/"
  to = "/pt"
  status = 302

# Fallback final
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers otimizados
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"